INSTALL_DIR=~/.config/mircmd/extensions/mircmd/chemistry-icons

.PHONY: install
install:
	rm -rf $(INSTALL_DIR)
	mkdir -p $(INSTALL_DIR)
	cp manifest.yaml $(INSTALL_DIR)/
	cp extension.json $(INSTALL_DIR)/
	cp -r icons $(INSTALL_DIR)/
